# This is a basic workflow to help you get started with Actions

name: CI Pipeline


on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
   - cron: "0 23 * * *"  


  workflow_dispatch:

jobs:
  unit_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
            repository: utibenoah/cineflixs

      
      - name: Install latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "npm"


      - name: Install dependencies
        run: npm install

        
      - name: Ensure Jest is executable
        run: chmod +x ./node_modules/.bin/jest


      

      - name: Run tests
        run: npm test
        
      - name: Upload unit test report
        uses: actions/upload-artifact@v5
        with:
          name: unit-test-report
          path: report/test-report.html   # make sure this path matches your actual HTML file

      - name: Download unit test report
        uses: actions/download-artifact@v5
        with:
          name: unit-test-report
          path: report-html/

      - name: List downloaded files
        run: ls -R report-html

      - name: Send HTML report to Slack
        run: |
          curl -F file=@report-html/test-report.html \
               -F "initial_comment=ðŸ“Š *Unit Test Report*" \
               -F channels=${{ secrets.SLACK_CHANNEL_ID }} \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload

     

      

